
import icons from './icons';

export default {
    'علامت': [
        { name: 'اهم', icon: icons.ohm },
        { name: 'کپی رایت', icon: icons.copyright },
    ],
    'ریاضی': [
        { name: 'x', icon: icons.x },
        { name: 'y', icon: icons.y },
        { name: 'آلفا', icon: icons.alpha },
        { name: 'اپسیلن', icon: icons.epsilon },
        { name: 'اجتماع', icon: icons.union },
        { name: 'اشتراک', icon: icons.intersection },
        { name: 'اهم', icon: icons.ohm },
        { name: 'بتا', icon: icons.beta },
        { name: 'برای همه', icon: icons.forAll },
        { name: 'بزرگتر مساوی', icon: icons.greaterEqual },
        { name: 'بزرگتر', icon: icons.greaterThan },
        { name: 'به اضافه منها', icon: icons.minusPlus },
        { name: 'به اضافه منها', icon: icons.plusMinus },
        { name: 'بینهایت', icon: icons.infinite },
        { name: 'پی', icon: icons.pi },
        { name: 'تتا', icon: icons.theta },
        { name: 'تساوی عینی', icon: icons.identicalEqual },
        { name: 'تقریب', icon: icons.approximately },
        { name: 'تقسیم', icon: icons.divide },
        { name: 'تهی', icon: icons.null },
        { name: 'دلتا', icon: icons.delta },
        { name: 'دیفرانسیل', icon: icons.differential },
        { name: 'زیرمجموعه', icon: icons.subsetOf },
        { name: 'سیگما', icon: icons.sigma },
        { name: 'عضو', icon: icons.elementOf },
        { name: 'کوچکتر مساوی', icon: icons.lessEqual },
        { name: 'کوچکتر', icon: icons.lessThan },
        { name: 'مساوی', icon: icons.equal },
        { name: 'مو', icon: icons.mu },
        { name: 'نا مساوی', icon: icons.notEqual },
    ],
};